"""Generated by scripts/sync-expert-notebooks.py; architectures exactly match cloud training."""
import math
import torch
from torch.nn import functional as F
from torchvision.models import resnet18, ResNet18_Weights

class ChangeExpert(torch.nn.Module):
    def __init__(self, vocabulary_size, answer_classes, pretrained=True):
        super().__init__()
        encoder = resnet18(weights=ResNet18_Weights.IMAGENET1K_V1 if pretrained else None)
        self.stem = torch.nn.Sequential(encoder.conv1, encoder.bn1, encoder.relu, encoder.maxpool,
            encoder.layer1, encoder.layer2, encoder.layer3, encoder.layer4)
        self.fuse = torch.nn.Sequential(torch.nn.Conv2d(2048, 512, 1, bias=False),
            torch.nn.BatchNorm2d(512), torch.nn.GELU(), torch.nn.Conv2d(512, 256, 3, padding=1),
            torch.nn.GELU())
        self.embedding = torch.nn.Embedding(vocabulary_size, 256, padding_idx=0)
        self.question = torch.nn.GRU(256, 256, batch_first=True, bidirectional=True)
        self.answer_head = torch.nn.Sequential(torch.nn.Linear(768, 512), torch.nn.GELU(),
            torch.nn.Dropout(0.2), torch.nn.Linear(512, answer_classes))
        self.mask_head = torch.nn.Sequential(torch.nn.Conv2d(256, 128, 3, padding=1),
            torch.nn.GELU(), torch.nn.Conv2d(128, 1, 1))

    def forward(self, time_a, time_b, tokens):
        feature_a, feature_b = self.stem(time_a), self.stem(time_b)
        fused = self.fuse(torch.cat([feature_a, feature_b, (feature_a-feature_b).abs(), feature_a*feature_b], 1))
        visual = F.adaptive_avg_pool2d(fused, 1).flatten(1)
        _, hidden = self.question(self.embedding(tokens))
        question = torch.cat([hidden[-2], hidden[-1]], 1)
        answer = self.answer_head(torch.cat([visual, question], 1))
        mask = F.interpolate(self.mask_head(fused), size=time_a.shape[-2:], mode="bilinear", align_corners=False)
        return answer, mask


class FusionExpert(torch.nn.Module):
    def __init__(self, backbone, embedding_dim: int, num_classes: int, image_size: int = 224):
        super().__init__()
        self.backbone = backbone
        self.norm = torch.nn.LayerNorm(embedding_dim)
        self.classifier = torch.nn.Linear(embedding_dim, num_classes)
        self.num_classes, self.image_size = num_classes, image_size

    def forward(self, *, s2=None, s1=None):
        inputs = {}
        if s2 is not None:
            inputs["S2L2A"] = s2
        if s1 is not None:
            inputs["S1GRD"] = s1
        if not inputs:
            raise ValueError("At least one modality is required")
        tokens = self.backbone(inputs)[-1]
        patch_logits = self.classifier(self.norm(tokens))
        class_logits = patch_logits.mean(1)
        side = math.isqrt(tokens.shape[1])
        if side * side != tokens.shape[1]:
            raise ValueError("Backbone tokens cannot be reshaped to a square evidence grid")
        evidence = patch_logits.transpose(1, 2).reshape(tokens.shape[0], self.num_classes, side, side)
        evidence = F.interpolate(evidence, (self.image_size, self.image_size), mode="bilinear", align_corners=False)
        return class_logits, evidence
