"""Mechanical source-of-truth sync: notebook architectures -> runtime, sensors -> ML."""
import ast
from pathlib import Path

import jupytext

root = Path(__file__).resolve().parents[1]
classes = []
for name, class_name in [("SatQuery_ChangeVQA_Training", "ChangeExpert"),
                         ("SatQuery_TerraMind_Fusion_Training", "FusionExpert")]:
    path = root / "notebooks" / f"{name}.py"
    source = path.read_text(encoding="utf-8")
    node = next(node for node in ast.parse(source).body if isinstance(node, ast.ClassDef) and node.name == class_name)
    classes.append(ast.get_source_segment(source, node))
    notebook = jupytext.reads(source.replace("# ruff: noqa: E402\n", "", 1), fmt="py:percent")
    path.with_suffix(".ipynb").write_text(jupytext.writes(notebook, fmt="ipynb"), encoding="utf-8", newline="\n")
header = ('"""Generated by scripts/sync-expert-notebooks.py; architectures exactly match cloud training."""\n'
          'import math\nimport torch\nfrom torch.nn import functional as F\n'
          'from torchvision.models import resnet18, ResNet18_Weights\n\n')
(root / "ml/satquery_ml/models/notebook_experts.py").write_text(header + "\n\n\n".join(classes) + "\n", encoding="utf-8", newline="\n")
(root / "ml/satquery_ml/sensors.py").write_text(
    (root / "backend/app/core/sensors.py").read_text(encoding="utf-8"), encoding="utf-8", newline="\n")
print("Synced two notebooks, exact runtime architectures, and metadata-only sensor profiles.")

# Replace unsafe numeric aliases with this exact sensor-aware implementation in all local readers.
for file, function, body in [
    ("backend/app/models/gateway.py", "_rgb_indexes", "from app.core.sensors import visual_indexes\n    return visual_indexes(dataset)"),
    ("backend/app/models/pair_tools.py", "_band_indexes", "from app.core.sensors import visual_indexes\n    if not visual:\n        return list(range(1, min(dataset.count, 2) + 1))\n    return visual_indexes(dataset)"),
    ("ml/satquery_ml/preprocessing.py", "rgb_band_indexes", "from satquery_ml.sensors import visual_indexes\n    return visual_indexes(source)"),
]:
    path = root / file
    source = path.read_text(encoding="utf-8")
    node = next(node for node in ast.parse(source).body if isinstance(node, ast.FunctionDef) and node.name == function)
    old = ast.get_source_segment(source, node)
    signature = old[:old.index("\n")]
    source = source.replace(old, signature + "\n    " + body, 1)
    path.write_text(source, encoding="utf-8", newline="\n")

server = root / "notebooks/SatQuery_Qwen3VL_Free_GPU_Server.py"
source = server.read_text(encoding="utf-8")
start = "# %% [markdown]\n# ## 6c. Learned intent planning"
end = "# %% [markdown]\n# ## 7. Verify the local HTTP contract"
if start in source:
    before, rest = source.split(start, 1)
    source = before + end + rest.split(end, 1)[1]
source = source.replace(end, start + "\n# No model retraining or new tunnel. Bounded JSON proposals only.\n\n# %%\n" +
                        (root / "notebooks/patches/planner_routes.py").read_text(encoding="utf-8") + "\n\n" + end, 1)
server.write_text(source, encoding="utf-8", newline="\n")
nb = jupytext.reads(source.replace("# ruff: noqa: E402\n", "", 1), fmt="py:percent")
server.with_suffix(".ipynb").write_text(jupytext.writes(nb, fmt="ipynb"), encoding="utf-8", newline="\n")
print("Synced learned planner cell and sensor-qualified readers.")

# One cell for an already-running Kaggle server: no dependency reinstall and no GPU restart.
sensor_source = (root / "backend/app/core/sensors.py").read_text(encoding="utf-8").replace("from __future__ import annotations\n", "")
quality_source = (root / "notebooks/patches/quality_upgrade.py").read_text(encoding="utf-8")
decode_node = next(node for node in ast.parse(quality_source).body if isinstance(node, ast.FunctionDef) and node.name == "quality_decode")
live_source = sensor_source + "\n\nrgb_band_indexes = visual_indexes\n\n" + ast.get_source_segment(quality_source, decode_node) + "\n\n" + (root / "notebooks/patches/planner_routes.py").read_text(encoding="utf-8")
(root / "notebooks/patches/live_planning_upgrade.py").write_text(live_source, encoding="utf-8", newline="\n")
live_nb = jupytext.reads(
    "# %% [markdown]\n# # Live planning + sensor-aware decoding upgrade\n# Paste the next code cell into your EXISTING Kaggle GPU server after 6b.\n# Interrupt only the section 10 wait, not the session. No weights are changed.\n# Run this cell, then resume section 10 if its attended window remains active.\n# This does not train or install the missing paired checkpoints.\n\n# %%\n" + live_source, fmt="py:percent")
(root / "notebooks/SatQuery_Live_Planning_Upgrade.ipynb").write_text(jupytext.writes(live_nb, fmt="ipynb"), encoding="utf-8", newline="\n")

# Sensor definitions must exist BEFORE the original server's base-image smoke test.
source = server.read_text(encoding="utf-8")
start_marker, end_marker = "# BEGIN SENSOR PROFILE RUNTIME", "# END SENSOR PROFILE RUNTIME"
if start_marker in source:
    before, rest = source.split(start_marker, 1)
    source = before + rest.split(end_marker, 1)[1]
needle = "def rgb_band_indexes(source: Any) -> list[int]:"
node = next(node for node in ast.parse(source).body if isinstance(node, ast.FunctionDef) and node.name == "rgb_band_indexes")
old = ast.get_source_segment(source, node)
source = source.replace(old, start_marker + "\n" + sensor_source + "\n" + end_marker + "\n" + needle + "\n    return visual_indexes(source)", 1)
server.write_text(source, encoding="utf-8", newline="\n")
nb = jupytext.reads(source.replace("# ruff: noqa: E402\n", "", 1), fmt="py:percent")
server.with_suffix(".ipynb").write_text(jupytext.writes(nb, fmt="ipynb"), encoding="utf-8", newline="\n")
print("Created live one-cell upgrade notebook and synchronized sensor-aware server.")

import json
runtime_files = {
    "satquery_ml/__init__.py": "", "satquery_ml/models/__init__.py": "",
    "satquery_model_service/__init__.py": "",
    "satquery_ml/models/notebook_experts.py": (root / "ml/satquery_ml/models/notebook_experts.py").read_text(encoding="utf-8"),
    "satquery_ml/sensors.py": sensor_source,
    "satquery_model_service/contracts.py": (root / "model_service/satquery_model_service/contracts.py").read_text(encoding="utf-8"),
    "satquery_model_service/paired_adapters.py": (root / "model_service/satquery_model_service/paired_adapters.py").read_text(encoding="utf-8"),
}
bundle = ("import sys, json, hashlib\nfrom pathlib import Path\n"
          "PAIR_RUNTIME_ROOT = Path('/kaggle/working/satquery_pair_runtime_v2')\n"
          "PAIR_RUNTIME_ROOT.mkdir(parents=True, exist_ok=True)\n"
          "runtime_files = json.loads(" + repr(json.dumps(runtime_files)) + ")\n"
          "for name, source in runtime_files.items():\n"
          "    target = PAIR_RUNTIME_ROOT / name\n    target.parent.mkdir(parents=True, exist_ok=True)\n"
          "    target.write_text(source, encoding='utf-8')\n"
          "if str(PAIR_RUNTIME_ROOT) not in sys.path:\n    sys.path.insert(0, str(PAIR_RUNTIME_ROOT))\n")
pair_source = ("# %% [markdown]\n# # Optional trained pair runtime — existing Kaggle session\n"
    "# Train the corrected ChangeVQA/TerraMind notebook first; attach its export as a private Kaggle input.\n"
    "# No training or artifact downloads happen here. Do not run a second GPU notebook just to keep a tunnel alive.\n"
    "# Fusion additionally requires terratorch from the fusion training environment.\n"
    "# Stop active requests before applying. Empty artifact paths deliberately load no pair expert.\n\n"
    "# %%\n" + bundle + "\n# %%\n" + (root / "notebooks/patches/paired_routes.py").read_text(encoding="utf-8"))
(root / "notebooks/SatQuery_Optional_Paired_Runtime.ipynb").write_text(
    jupytext.writes(jupytext.reads(pair_source, fmt="py:percent"), fmt="ipynb"), encoding="utf-8", newline="\n")
print("Bundled optional paired runtime with exactly the training architectures, not remote executable code.")
